### ISSUE TITLE
EPIC - As a teacher, I would like an easy way of viewing trends with my students grades this could include graphs of grades over time and also show the impact on students grades after a specific grade was put in.

### ISSUE THREAD

**Issue by dannirash** [CEN3031-3F/Emerald-Project03-3f#6]
Acceptance Criteria:

- [ ] System should provide a user-friendly dashboard that allows the teacher to view an overview of student’s grades and trends
- [ ] Allow teachers to be able to generate and view graphs of their students' assessment results.
- [ ] Allow the teacher to inspect a certain grade or event.
- [ ] Be able to filter and sort through students' data.
- [ ] Provide an option to export the results to the user's computer.

Tasks:

- [ ] Design the Teacher’s Dashboard
- [ ] Implement Graph Generation
- [ ] Implement Grade Impact Analysis
- [ ] Add Filtering and Sorting Options
- [ ] Enable Export and Sharing
