### ISSUE TITLE
EPIC - As a student who might need more help than others, I would like to have an infrastructure that helps me learn. This could be through links to external resources, or maybe a teacher could provide hints if a student gets stuck on a question.

### ISSUE THREAD

**Issue by dannirash** [CEN3031-3F/Emerald-Project03-3f#8]
Acceptance Criteria:

- [ ] Should provide links to relevant external resources within the assessments as provided by the teacher. 
- [ ] Allow students to access these external resources.
- [ ] Give the ability to allow students to ask for hints on a question if they are stuck.
- [ ] Give teachers the ability to directly give the students hints or guidance on the assessments.
- [ ] Maintain a record of when hints are given to certain students.

Tasks:

- [ ] Integrate External Resources
- [ ] Develop Resource Access Interface
- [ ] Implement Request for Hints
- [ ] Teacher Hint and Guidance Feature
- [ ] Progress and Support Tracking
