### ISSUE TITLE
EPIC - As a student who cares about my grade, I would benefit from understanding assessment point values and question point values.

### ISSUE THREAD

**Issue by dannirash** [CEN3031-3F/Emerald-Project03-3f#9]
Acceptance Criteria:

- [ ] Clearly display the total point value of each assessment to students.
- [ ] Display each individual point value for a question.
- [ ] Allow students to see their progress in terms of points earned as they complete the assessment.
- [ ] Allow point values to be viewed before and during the assessment.
- [ ] Promptly display any changes to the point values to the students view.

Tasks:
- [ ] Total Assessment Point Display
- [ ] Individual Question Point Display
- [ ] Real-Time Progress Tracking
- [ ] Pre-Assessment Point Visibility
- [ ] Point Value Change Handling
